version: '3.3'
services:
  client-ui:
    image: faresramchani/vuejs-app:latest
    restart: always
    ports:
      - '5173:5173'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
