version: '3'
services:
  client-ui:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    env_file:
      - .env.development
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
