name: Pipeline CI/CD vuejs App

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/vuejs-app:${{ github.run_number }}
  IMAGE_LATEST: ${{ secrets.DOCKERHUB_USERNAME }}/vuejs-app:latest

jobs:
  unit-test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: |
          npm ci
          npm run build

  build-and-push-job:
    runs-on: ubuntu-latest
    needs: unit-test-job
    steps:
      - uses: actions/checkout@v4

      - run: |
          docker build -f Dockerfile.prod -t ${{ env.IMAGE_NAME }} .
          docker tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_LATEST }}

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: |
          docker push ${{ env.IMAGE_NAME }}
          docker push ${{ env.IMAGE_LATEST }}

  deploy-job:
    runs-on: ubuntu-latest
    needs: build-and-push-job
    steps:
      - uses: actions/checkout@v4

      - name: Copy docker-compose.prod.yml to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: docker-compose.prod.yml
          target: /home/${{ secrets.VPS_USERNAME }}/apps/vuejs-app/

      - name: Upload .env.prod to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            mkdir -p ~/apps/vuejs-app
            cat << 'EOF' > ~/apps/vuejs-app/.env
            ${{ secrets.ENV_PROD_FILE }}
            EOF

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~/apps/vuejs-app
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker pull ${{ env.IMAGE_LATEST }}
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d --build
